//
//  Extension+Color.swift
//  MiaSwiftUIExample
//
//  Created on November 21, 2025.
//  Copyright © 2025 Mia21. All rights reserved.
//
//  Description:
//  Color and LinearGradient extensions providing app-specific gradients.
//  Note: Color assets are auto-generated by Xcode and available directly.
//

import SwiftUI

// MARK: - Linear Gradient

extension LinearGradient {
  static var appGradient: LinearGradient {
    LinearGradient(
      gradient: Gradient(colors: [.gradientBlue, .gradientPurple]),
      startPoint: .topLeading,
      endPoint: .bottomTrailing
    )
  }
}
